version: "3.8"
services:
  db:
    image: postgres

    restart: always

    environment:
      POSTGRES_USER: laundbot
      POSTGRES_PASSWORD: laundbot
      POSTGRES_DB: laundbotdb

    ports:
      - "5432:5432"

    volumes:
      - ./data/db:/var/lib/postgresql/data

  adminer:
    image: adminer

    restart: always

    ports:
      - "8080:8080"
